id: A627F6A7D
title: Prayer to the Lineage of Vajra Akṣobhya
type: translation
pechas:
- I6A77FF7A
- I7B1E7AB1
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:14:33.852579
  last_modified_at: 2023-01-04 12:14:33.852586
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  I6A77FF7A/1D0B: E9F5
  I7B1E7AB1/FFE5: E9F5
